# ??????
# @author <a href="https://github.com/liyupi">?????</a>
# @from <a href=" https://tsingfeng.cn">????????</a>
spring:
  application:
    name: tsingoj-backend-user-service
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    store-type: redis
    # 30 ???
    timeout: 2592000
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tsingoj
    username: root
    password: 123456
  # Redis ??
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      # ????
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 182.92.202.251:8848
server:
  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api/user
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?
# ??????
codesandbox:
  type: remote
knife4j:
  enable: true
oj:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: tsingoj
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    #用户
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication