spring:
  cloud:
    nacos:
      discovery:
        server-addr: 182.92.202.251:8848
    gateway:
      routes:
        - id: tsingoj-backend-user-service
          uri: lb://tsingoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: tsingoj-backend-question-service
          uri: lb://tsingoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: tsingoj-backend-judge-service
          uri: lb://tsingoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: tsingoj-backend-gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
server:
  port: 8121
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
#oj:
#  jwt:
#    # 设置jwt签名加密时使用的秘钥
#    admin-secret-key: itcast
#    # 设置jwt过期时间
#    admin-ttl: 7200000
#    # 设置前端传递过来的令牌名称
#    admin-token-name: token
#
#    #用户
#    user-secret-key: itheima
#    user-ttl: 7200000
#    user-token-name: authentication